name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build JSDoc
      uses: andstor/jsdoc-action@v1
      with:
          source_dir: .
          recurse: true
          output_dir: ./out
          config_file: conf.json
          template_name: minami
          front_page: README.md

    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out

    - run: npm install
#     - run: npm run build --if-present
#     - run: npm test
      env:
        CI: true
